# Generated by Django 5.2.6 on 2025-10-07 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_agendamento_servico'),
        ('funcionarios', '0002_alter_funcionario_options'),
        ('servicos', '0006_alter_servico_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-horario'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(default='A', help_text='Status do agendamento', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='ordemservicos',
            name='agendamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='agendamentos.agendamento', verbose_name='Agendamento'),
        ),
        migrations.AlterField(
            model_name='ordemservicos',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='funcionarios.funcionario', verbose_name='Funcionario'),
        ),
        migrations.AlterField(
            model_name='ordemservicos',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_servico', to='servicos.servico', verbose_name='Serviço'),
        ),
    ]
