# Generated by Django 5.2.6 on 2025-10-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do serviço', max_length=100, unique=True, verbose_name='Serviço')),
                ('descricao', models.CharField(help_text='Descrição do serviço', max_length=300, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do serviço', max_digits=5, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
