# Generated by Django 5.2.6 on 2025-10-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(help_text='Descrição do serviço', max_length=300, verbose_name='Descrição'),
        ),
    ]
