# Generated by Django 5.2.6 on 2025-10-07 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('servicos', '0002_alter_servico_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Quantidade do produto', max_digits=5, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(help_text='Nome do produto utilizado', on_delete=django.db.models.deletion.PROTECT, related_name='produto', to='produtos.produto', verbose_name='Produto')),
                ('servico', models.ForeignKey(help_text='Nome do serviço utilizado', on_delete=django.db.models.deletion.PROTECT, related_name='servico', to='servicos.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Produto utilizado',
                'verbose_name_plural': 'Produtos utilizados',
            },
        ),
    ]
