# Generated by Django 5.2.6 on 2025-10-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_produtosservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosservico',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, help_text='Quantidade utilizada do produto', max_digits=5, verbose_name='Quantidade'),
        ),
    ]
