# Generated by Django 5.2.6 on 2025-10-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('servicos', '0004_alter_produtosservico_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='produto',
            field=models.ManyToManyField(through='servicos.ProdutosServico', to='produtos.produto'),
        ),
    ]
