# Generated by Django 5.2.6 on 2025-10-07 08:00

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_servico_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': [django.db.models.functions.text.Upper('nome')], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
    ]
